/**
 * The scraper bot feature's documentation articles.
 *
 * Three articles: what the feature is and how a run actually works, how a
 * profile is built and validated, and how captured messages and capture rules
 * turn raw scraper output into a searchable table. Each links the other two,
 * plus the two general-purpose siblings a reader of this feature is likely to
 * want next.
 */

import type { DocArticle } from '../../core/registry';

export const BOT_DOCS: DocArticle[] = [
  {
    id: 'bot.overview',
    title: 'The scraper bot',
    category: 'Scraper bot',
    body: [
      '## What this is',
      '',
      'World Downloader Studio captures whatever chunks a Minecraft client actually',
      'loads. This feature does not capture anything itself — it runs the bundled',
      'Node scraper (`scraper/scrape.js` in the project checkout), a small',
      'mineflayer-based client that logs in, walks or flies a grid of waypoints and',
      'then disconnects. Point it at the downloader proxy and the world gets loaded,',
      'chunk by chunk, without a person sitting at the keyboard.',
      '',
      'This tab is a control surface over that real process. There is no simulation',
      'anywhere in it: starting a run spawns `node scrape.js --config <file>` through',
      'the application\'s privileged process bridge, the run log is that process\'s',
      'actual stdout and stderr, and stopping a run sends it a real signal.',
      '',
      '## The pieces',
      '',
      '- **Profiles** — the scraper\'s configuration, saved so you do not retype it.',
      '  See [Profiles and presets](bot.profiles).',
      '- **Run controls** — pick a profile, start it, watch its phase, stop it.',
      '- **Run log** — every line the scraper printed, verbatim, filterable by',
      '  severity and searchable with the full pattern builder.',
      '- **Captured messages and capture rules** — turns matching lines into a',
      '  sortable table. See [Captured messages and capture rules](bot.captureRules).',
      '',
      '## Before you start a run',
      '',
      'Start the world downloader\'s proxy first. The proxy is what actually writes',
      'chunks to disk; the scraper only causes chunks to load by walking through',
      'them. A profile also needs a scraper folder — either set on the profile itself',
      'or once in this feature\'s settings — pointing at the folder that contains',
      '`scrape.js`. The run controls refuse to start, and say exactly why, until both',
      'a usable profile and a real `scrape.js` are in place.',
      '',
      '## What a run actually does',
      '',
      '1. The chosen profile is validated. Every problem is named in plain words —',
      '   not just "invalid", but which field and what to do about it.',
      '2. A configuration file is generated from the profile and written to the',
      '   application\'s own data folder, alongside a place for the visited-chunk',
      '   cache if the profile did not name one.',
      '3. `node scrape.js --config <file>` is spawned in the scraper\'s folder.',
      '4. Every stdout and stderr line arrives on the process push channel, is',
      '   classified by severity, appended to the run log, and — if the setting is',
      '   on — run through the capture rules.',
      '5. On exit, the outcome (clean exit, signal, or a non-zero code) is recorded',
      '   in local history and the generated configuration file is overwritten so',
      '   the AuthMe password it may have carried does not sit on disk.',
      '',
      '## Microsoft accounts',
      '',
      'A Microsoft account\'s first sign-in prints a device code, which the run',
      'controls surface as its own panel with a one-click link to the sign-in page.',
      'After that one-time step the scraper caches the token itself.',
      '',
      '## Reopening the tab mid-run',
      '',
      'If a run was started and the tab is reopened, the panel reattaches to the',
      'still-running process rather than losing track of it: it reads back the',
      'output collected so far and keeps listening for what comes next.',
      '',
      '## Security notes',
      '',
      'A stored AuthMe password lives in the operating system credential vault, not',
      'in the settings file. It is written into the generated configuration file only',
      'for the length of a run, and that file is wiped the moment the run ends. The',
      'password is never shown back on screen, never logged, and never leaves the',
      'machine — the only network traffic this feature causes is the scraper\'s own',
      'Minecraft connection to the proxy address in the profile.',
    ].join('\n'),
    related: ['bot.profiles', 'bot.captureRules', 'history.panel', 'settings.surface']
  },
  {
    id: 'bot.profiles',
    title: 'Profiles and presets',
    category: 'Scraper bot',
    body: [
      '## What a profile is',
      '',
      'A profile is the scraper\'s own configuration file, kept as an editable record',
      'so it does not need retyping. Every field on the editor maps onto a key the',
      'bundled scraper\'s `loadConfig` actually reads — nothing is written that the',
      'scraper would ignore, because a setting that silently does nothing is worse',
      'than one that is simply absent.',
      '',
      '## Starting from a preset',
      '',
      'An empty profile list offers five presets: the scraper\'s own compiled-in',
      'defaults, a walk-the-area-around-spawn profile, a large flying sweep, a slow',
      'pass tuned for automatic container opening, and a resume profile for picking',
      'an interrupted sweep back up. Every preset card states exactly which fields it',
      'sets before you use it, so choosing one is an informed action rather than a',
      'guess. What comes out is an ordinary profile — every field stays editable',
      'afterwards, and nothing about it is special or protected.',
      '',
      '## The fields, grouped',
      '',
      '- **Identity** — the name, the per-profile scraper folder override, notes.',
      '- **Connection** — the proxy address and port (never the real server) and the',
      '  protocol version, with a picker seeded from the versions your own scraper',
      '  install actually has plus whatever other profiles already use.',
      '- **Accounts** — one row per bot. Offline names must be 3–16 letters, digits',
      '  or underscores; Microsoft accounts sign in by email. The area to cover is',
      '  split between however many accounts are listed.',
      '- **Area** — centre and radius, an explicit bounding box, or an around-each-',
      '  spawn mode where every bot builds its own grid. A live estimate shows',
      '  roughly how many chunks that means.',
      '- **Movement** — fly or walk per game mode, and the altitude to fly at.',
      '- **Timing** — how long to wait at a chunk, at a waypoint before giving up on',
      '  it, for a container to finish opening, and after finishing before',
      '  disconnecting (so the proxy has time to flush the last writes).',
      '- **Deduplication** — where the visited-chunk cache lives, and whether a run',
      '  should ignore it and walk everything again.',
      '- **Automatic login** — an optional stored AuthMe-style password, held in the',
      '  credential vault and never shown back on screen.',
      '',
      '## Validation',
      '',
      'Every field is checked live, in plain words that say what to fix — never a',
      'bare "invalid". A profile can be saved while it still has problems; nothing is',
      'lost by saving half-finished work. A run simply refuses to start until the',
      'list is empty, and the start button names the first unmet condition instead of',
      'sitting there disabled with no explanation.',
      '',
      '## Working with several profiles at once',
      '',
      'The profile list carries the full bulk-action set: multi-select with a',
      'keyboard path, select-the-shown versus select-every-profile (each honestly',
      'labelled), invert selection, duplicate (which deliberately drops the stored',
      'password rather than sharing one credential-vault entry between two',
      'profiles), export, and delete behind the two-key destructive-action gate.',
      'Deleting a profile also deletes any password it stored in the vault; captured',
      'messages and the visited-chunk cache are untouched either way.',
    ].join('\n'),
    related: ['bot.overview', 'bot.captureRules', 'history.panel']
  },
  {
    id: 'bot.captureRules',
    title: 'Captured messages and capture rules',
    category: 'Scraper bot',
    body: [
      '## What gets captured',
      '',
      'Every line a run prints lands in the run log verbatim, unconditionally. A',
      '**capture rule** is a separate, additional step: a regular expression that,',
      'when it matches a line, turns that line into a row in the captured-messages',
      'table — with a sender, a channel, a timestamp and the message text pulled out',
      'of the match. A line no rule matches still shows up in the run log; it just',
      'never becomes a row.',
      '',
      'The scraper as shipped is a chunk-loading tool, not a chat client: it reports',
      'its own sign-in, progress, kicks and errors, but it does not echo the',
      'server\'s chat. The shipped rules match exactly those shapes. To capture actual',
      'chat, import a server or console log file that contains it — the same capture',
      'rules run over an imported file as over live output, and every row states',
      'plainly whether it came from a run or an import.',
      '',
      '## The shipped rules',
      '',
      'Chat line, server-console chat line, kick or disconnect reason, bot error,',
      'sign-in message, Microsoft device code, and progress report. Each can be',
      'turned off, edited in place, or opened in the full anchored pattern builder',
      'for a proper look at what it matches. Turning off a shipped rule does not',
      'delete it — restoring the shipped set brings it straight back, and anything it',
      'already captured is untouched either way.',
      '',
      '## Writing your own rule',
      '',
      'A new rule starts as `^(.+)$` against the `system` channel, which matches',
      'every line whole — a safe, obviously-visible starting point to narrow down',
      'from. Only the pattern, the channel and a sender template need setting:',
      '`{1}`, `{2}` and so on inside the sender template pull in that capture group',
      'from the match. A rule you wrote yourself, once deleted, is gone for good —',
      'unlike a shipped rule, there is nothing to restore it from.',
      '',
      '## Working with the table',
      '',
      'The table sorts, filters by channel, and searches through the full pattern',
      'builder like every other search field in the application. Rows can be',
      'tagged and untagged in bulk with your own labels — the tag picker offers',
      'every tag already in use, seeded from real data rather than a blank box.',
      'Selection follows the same honest-scope rules as the profile list: select the',
      'shown rows, select every captured message, or invert the current selection,',
      'each stating plainly which it means. Export honours whatever filter is',
      'currently active. Deleting a selection, or clearing the whole table, goes',
      'through the destructive-action gate and names exactly what will and will not',
      'be affected — profiles, the run log and the visited-chunk cache are never',
      'touched by clearing captured messages.',
    ].join('\n'),
    related: ['bot.overview', 'bot.profiles']
  }
];
