import type { DocArticle } from '../../core/registry';

/**
 * In-app documentation for the bot-chat surface.
 *
 * These articles are bundled into the build and rendered through the shared
 * markdown renderer inside the application's own documentation browser. They
 * are a companion to, not a replacement for, `docs/features/mineflayer-chat.md`
 * in the repository, which is the deeper reference aimed at a maintainer
 * reading source rather than using the app.
 */
export const MINEFLAYER_CHAT_DOCS: DocArticle[] = [
  {
    id: 'mineflayer-chat.overview',
    title: 'Bot chat',
    category: 'Bot chat',
    body: [
      '# Bot chat',
      '',
      'This surface shows every message the connected bot receives, lets you send',
      'one back, and draws the text surfaces the server paints outside the chat',
      'box: the tab list, boss bars, scoreboards, teams, titles and the action bar.',
      '',
      'It never opens a connection of its own. The connection is owned by the',
      '**Bot control** feature; open that first and connect a bot, and this',
      'surface follows whichever session comes into focus. Disconnecting there',
      'empties every panel here honestly rather than leaving stale numbers on',
      'screen.',
      '',
      '## The message log',
      '',
      'Every message is kept with its channel — `chat` for a player message,',
      '`system` for a message with no sender (joins, leaves, deaths, plugin',
      'text), `game_info` for the line the game floats above the hotbar, and a',
      'fourth channel, `outgoing`, that is not a server channel at all: it is',
      'this surface’s own record of what it asked the bot to say, kept apart so',
      'it is never mistaken for something the server sent back.',
      '',
      'The log is held in memory only and bounded by a retention setting (default',
      '2000 messages, 100 to 20000). When it is full the oldest message is',
      'dropped and the dropped count is shown above the log, so a gap is visible',
      'rather than silent. Nothing here is ever written to disk.',
      '',
      '## Formatting',
      '',
      'The game sends chat in one of two shapes: an older section-sign string',
      '(`§c` for red, `§l` for bold, `§r` to reset) or a modern component tree',
      'carrying `color`, `bold`, `italic`, `underlined` and `strikethrough`.',
      'Both are turned into real styled runs and drawn with real CSS — never a',
      'wall of section signs and never raw JSON. The sixteen vanilla colours are',
      'the game’s own colours: they identify who is speaking, so they do not',
      'follow your seed colour, though the exact shade is still reachable from',
      '**Edit appearance…** on the run like any other colour in the application.',
      '',
      'Obfuscated text keeps its real words in the DOM at all times — copying,',
      'exporting and a screen reader all get the actual text the server sent.',
      'The visual scramble is a CSS flicker only, and it stands down completely',
      'when reduced motion is requested.',
      '',
      '## Sending',
      '',
      'The composer sends a public message, a whisper to one player, or a',
      'command — all three through the bot that is connected right now. A',
      'command is sent to the server exactly as typed (a leading slash is added',
      'if you forget it); what it does is entirely up to the server and cannot',
      'be undone from here.',
      '',
      'The character counter follows the server’s own chat length limit, which',
      'the library derives from the protocol version. Going over it does not',
      'block sending: the library splits the message into several lines, and the',
      'counter says how many.'
    ].join('\n'),
    related: ['mineflayer-chat.rules', 'mineflayer-chat.server']
  },
  {
    id: 'mineflayer-chat.rules',
    title: 'Chat pattern rules',
    category: 'Bot chat',
    body: [
      '# Chat pattern rules',
      '',
      'A rule matches incoming messages against a regular expression and takes',
      'one action: show a notification, reply in chat, run a command, or stop —',
      'which skips every rule below it for that one message.',
      '',
      '## What a rule can never do',
      '',
      'A rule only ever looks at `chat`, `system` and `game_info` messages. It',
      'never sees a message this surface itself sent (the `outgoing` channel is',
      'excluded entirely), and it never sees a message from the bot’s own',
      'username. Both exclusions exist for the same reason: without them a reply',
      'rule could match its own reply and end up in conversation with itself for',
      'as long as the server let it.',
      '',
      '## Speaking on your behalf',
      '',
      'A rule whose action is **Reply in chat** or **Run a command** sends',
      'through the bot under your account, without asking again each time it',
      'fires. Because of that:',
      '',
      '- Every such rule carries a cooldown that cannot go below two seconds.',
      '- Every reply and command a rule sends also draws on a shared',
      '  reply budget — a ceiling on how many messages every rule together may',
      '  send in one minute, independent of each rule’s own cooldown. Reaching it',
      '  raises a warning instead of sending. Setting the budget to zero silences',
      '  every rule that speaks while notification rules keep working.',
      '- The editor shows exactly what a rule will do — the channels it watches,',
      '  the text it will send, and how often — before it can be armed.',
      '- Every reply or command a rule actually sends is written to local',
      '  version history, so what happened while you were away is auditable',
      '  after the fact.',
      '',
      '## The pattern',
      '',
      'A rule matches against the message with its formatting removed — the',
      'plain words, not the section signs or the component tree. Open the',
      'pattern builder from the pattern field to compose it and try it against',
      'real text before saving. `$0` in a reply or command payload is replaced',
      'with the whole match, and `$1` through `$9` with the pattern’s capture',
      'groups.',
      '',
      '## Failure modes',
      '',
      '- **The bot is not connected.** A rule still matches and still tries; a',
      '  reply or command that cannot be sent raises a warning rather than being',
      '  silently dropped.',
      '- **The pattern does not compile.** An invalid pattern is treated as a',
      '  pattern that matches nothing, and the editor refuses to save until it',
      '  compiles.',
      '- **The master switch is off.** Turning off “Run the pattern rules” in',
      '  settings stops every rule from matching at once, without touching any',
      '  rule’s own enabled state — the fastest way to go quiet in a hurry.'
    ].join('\n'),
    related: ['mineflayer-chat.overview', 'mineflayer-chat.server']
  },
  {
    id: 'mineflayer-chat.server',
    title: 'Server text surfaces',
    category: 'Bot chat',
    body: [
      '# Server text surfaces',
      '',
      'Minecraft draws several things outside the chat box: the tab list (who is',
      'online, their ping and game mode), boss bars, scoreboards, teams, and the',
      'title and subtitle painted across the middle of the screen. This tab shows',
      'all of it, read from the connected bot’s own live state.',
      '',
      'Every value here is the real event value the library received. While no',
      'bot is connected, or immediately after one disconnects, every panel is',
      'honestly empty rather than showing the last thing it saw as though it',
      'were still true.',
      '',
      '## Refreshing',
      '',
      'Most of this state updates itself as the server sends new events. The',
      '**Re-read the server state** action asks the currently connected session',
      'for everything again in one pass, which is useful right after connecting',
      'or after a long idle period where an event might plausibly have been',
      'missed.',
      '',
      '## Colour and formatting',
      '',
      'Tab list headers and footers, boss bar titles, scoreboard titles and',
      'entries, and team names, prefixes and suffixes can all carry the game’s',
      'own formatting codes, exactly like a chat message. They are rendered the',
      'same way chat is: real styled runs, never a raw section-sign string.'
    ].join('\n'),
    related: ['mineflayer-chat.overview', 'mineflayer-chat.rules']
  }
];
