import type { DocArticle } from '../../core/registry';

/**
 * Documentation for the movement surface.
 *
 * Two articles: what the surface does and how it is wired to a bot session, and
 * the one behaviour that took the most care to get right — a held control that
 * releases the instant it stops being genuinely held.
 */
export const MOVEMENT_DOCS: DocArticle[] = [
  {
    id: 'mineflayerMovement.overview',
    title: 'Piloting the bot: movement, look and ray tracing',
    category: 'Bot movement',
    body: [
      'This surface drives the seven directional and modifier controls the vendored',
      '`mineflayer` library exposes (`lib/plugins/physics.js`), turns the bot to face',
      'a point or an entity, casts the same ray trace the library uses for block and',
      'entity targeting, walks it in a straight line to a coordinate, and follows an',
      'entity at a held distance.',
      '',
      '## Where the session comes from',
      '',
      'This feature never opens a connection itself. It looks for a bot session',
      'module published by the `mineflayer` feature at `features/mineflayer/index.ts`,',
      'accepting any of a named export (`movementSession`, `botSession`,',
      '`mineflayerSession`, `session`), a factory function, a multi-bot session host,',
      'or a runtime registration through `window.mineflayerMovement.provideSession(...)`',
      'and `provideHost(...)`. The exact list is shown on screen whenever nothing is',
      'found, rather than a generic "not connected" — a missing module and a bot that',
      'genuinely disconnected are different problems and get different messages.',
      '',
      '## Directional controls',
      '',
      'Forward, back, left, right, jump, sprint and sneak are held exactly as long as',
      'the pointer or the key that started them is held. Releasing the pointer,',
      'releasing the key, or the pad losing focus for any reason — clicking',
      'elsewhere, Alt+Tab, a dialog opening — releases that control immediately. See',
      '"Why a held control always lets go" for the exact mechanism.',
      '',
      'Keyboard piloting (a setting, on by default) lets W, A, S, D, Space, Shift and',
      'Ctrl drive the pad while the pad itself has focus, scoped so that typing those',
      'letters into a coordinate field is just typing. Every button also holds with',
      'Space or Enter regardless of that setting, so keyboard operation is never lost',
      'entirely.',
      '',
      '## Look',
      '',
      'Yaw and pitch are entered in degrees and converted to the radians the library',
      'takes; the read-out shows both units. "Look at a point" and "look at an',
      'entity" compute the same `yaw = atan2(-dx, -dz)`, `pitch = atan2(dy, sqrt(dx²',
      '+ dz²))` the library itself uses in `bot.lookAt`, so the preview and the real',
      'call never disagree about which way the bot will turn. The "send the exact',
      'angle" option passes `force` through to the library, skipping the smooth',
      'server-side turn — useful before dropping an item or shooting, unnecessary for',
      'ordinary walking.',
      '',
      '## Ray-trace target picker',
      '',
      'Casts from the bot eye along its current facing using `blockAtCursor` and',
      '`entityAtCursor`, exactly as the vendored `lib/plugins/ray_trace.js` exposes',
      'them, including their real distance limits (configurable in settings). A',
      'session that has not wired up a ray-trace route says so and the buttons',
      'disable with that exact reason, rather than firing into nothing. Whatever the',
      'ray hits can be copied straight into the walk or look-at-a-point coordinates,',
      'so a target found by looking never has to be typed.',
      '',
      '## Walk to coordinates',
      '',
      'A straight-line walk, not a navigated path: the bot faces the target and',
      'walks, re-aiming on a configurable tick, hopping over a one-block step when it',
      'stops making measurable progress. It stops itself — reporting the metres',
      'remaining — on arrival (within the arrive radius, measured on X and Z only),',
      'on cancellation, when progress stalls past the stuck timeout, when the walk',
      'timeout is reached, or if the bot disconnects mid-walk. Only one walk or one',
      'follow may run at a time; starting the other is refused with the reason.',
      '',
      '## Follow an entity',
      '',
      'Holds a chosen distance to a nearby entity: walks when further away than that',
      'distance, stands still when closer, and stops itself the moment the entity',
      'leaves the bot\'s own entity list rather than continuing to chase a ghost.',
      '',
      '## Route preview',
      '',
      'A top-down diagram of the current walk or follow: start, target, the bot\'s',
      'current position and the ground already covered, bounded to a configurable',
      'trail length. The vendored library ships forty-one plugins and none of them',
      'plans a route, so the line drawn is always the literal straight line the bot',
      'is attempting — the preview says this plainly rather than implying navigation',
      'that is not there. If a session ever does expose a `pathfinder`, its own',
      'reported waypoints are drawn instead and named as such.',
      '',
      '## The movement log',
      '',
      'Every control press and release, look, walk, follow and ray trace is recorded',
      'as it genuinely happens — never predicted, never simulated. The log carries a',
      'search field with the full pattern builder, multi-select with an honestly',
      'scoped select-all, an inverse selection, bulk delete behind the destructive-',
      'action gate, and export in every format the application supports. It is',
      'bounded to a configurable entry count; when the oldest entries are dropped to',
      'stay under that limit, the drop is reported rather than silent.'
    ].join('\n'),
    related: ['mineflayerMovement.holdRelease', 'core.overview', 'core.regex']
  },
  {
    id: 'mineflayerMovement.holdRelease',
    title: 'Why a held control always lets go',
    category: 'Bot movement',
    body: [
      'A directional pad that can leave a control held after the thing holding it is',
      'gone is a bot that keeps walking into a wall, off a ledge, or into a mob, with',
      'nobody driving. This surface treats that as the one defect it exists to',
      'prevent, and every release path is real and independently wired rather than',
      'relying on one mechanism to catch every case.',
      '',
      '## Pointer hold',
      '',
      'A control button captures the pointer on press (`setPointerCapture`), so the',
      'release fires on that exact element even if the pointer drifts off the button',
      'before it lifts. Release fires on pointer up, pointer cancel, and loss of',
      'pointer capture for any reason.',
      '',
      '## Keyboard hold',
      '',
      'Space or Enter on a control button holds it on key-down and releases it on',
      'key-up, the same as the pointer path. With keyboard piloting on, W, A, S, D,',
      'Space, Shift and Ctrl do the same while the pad container itself has focus,',
      'and Escape releases every control at once.',
      '',
      '## The blur path — the one this article is really about',
      '',
      'Every control button releases the instant it individually loses focus, and the',
      'pad container additionally releases every control the moment focus leaves the',
      'pad entirely — a click elsewhere, a dialog opening, Tab moving on, a palette',
      'command firing. The window itself losing focus (Alt+Tab, a virtual-desktop',
      'switch, the operating system taking a screenshot) releases every control too,',
      'because none of those events reliably fire a DOM blur on the exact element',
      'that was held. A control is never left holding on the strength of one',
      'listener; it is released redundantly by design.',
      '',
      '## What "release" actually sends',
      '',
      'Releasing a control calls the session\'s real `setControlState(control, false)`',
      '(or `clearControlStates()` for a full release) — never a local visual change',
      'only. If the session call itself fails, that failure is recorded in the',
      'movement log rather than assumed to have succeeded.',
      '',
      '## Verifying it',
      '',
      'Hold a control with the pointer, drag off the button before releasing, and',
      'confirm the read-out shows it released. Hold with Space, then Tab away',
      'without releasing the key, and confirm the same. Hold with the keyboard pad',
      'focused, then Alt+Tab to another application, and confirm every control shows',
      'released when you return.'
    ].join('\n'),
    related: ['mineflayerMovement.overview', 'core.overview']
  }
];
