import type { DocArticle } from '../../core/registry';

/**
 * The in-application documentation article, mirroring
 * `docs/features/world-vault.md`.
 */
export const WORLD_VAULT_DOCS: DocArticle[] = [
  {
    id: 'world-vault.overview',
    title: 'World vault',
    category: 'World vault',
    related: ['worlddownload.overview', 'map.overview', 'history.overview', 'export.overview', 'settings.overview'],
    body: [
      '# World vault',
      '',
      'A downloaded Minecraft world becomes a real Git repository. This feature',
      'creates that repository, watches the world folder while a download is in',
      'progress and commits automatically once writes have gone quiet, keeps',
      'unlimited, append-only undo across every commit, and — only when a person',
      'explicitly asks — publishes the whole thing to a remote.',
      '',
      'It also publishes a small typed contract (`contract.ts`) that its two',
      'sibling features import directly: **world-vault-renders** (an optional map',
      'render per commit) and **world-vault-edit** (chunk operations driven from',
      'the rendered map). Neither sibling reimplements any of the git logic here;',
      'both call into this feature\'s git operations through the privileged bridge',
      '(`ctx.studio.worldVault.*`) and this file\'s own exported helpers.',
      '',
      '## Where the repository lives, and why',
      '',
      'The vault is a real `git` repository at `<worldPath>/.git` — **inside** the',
      'world\'s own folder, not beside it. Inside wins because the vault travels',
      'with the world: copy the folder, rename it, move it to another machine —',
      'the history comes along, because it never left. A managed block in',
      '`.gitignore` excludes `session.lock` and a handful of OS/temp artefacts',
      'that are not world data and would otherwise create churn on every session',
      'start with nothing meaningful captured.',
      '',
      '## Hazard 1: never commit mid-write',
      '',
      'A region file is rewritten continuously while chunks stream in. The',
      'background runner tracks, per file, the last time its size or',
      'modification time changed, and only commits once every currently-dirty',
      'file has gone quiet for a full **quiet period** (default 8s, a real,',
      'adjustable setting) — never on the poll that first notices activity. The',
      'decision is a pure function (`computeSettleDecision`) with no I/O, unit',
      'tested directly.',
      '',
      '## Hazard 2: bounding the growth honestly',
      '',
      'Standard Git LFS is prohibited project-wide. This feature shows the',
      'vault\'s size on disk (history and working tree, separately) at all times,',
      'offers a safe **Compact history** (`git gc`, never removes a commit), and',
      'a genuinely destructive **Prune**: squashes everything before a chosen',
      'commit into one new root via real Git plumbing (`git commit-tree` +',
      '`git rebase --onto`), reclaiming the disk space those commits used. Prune',
      'is gated behind the two-key confirm dialog and states exactly what is',
      'about to become unrecoverable before it runs.',
      '',
      '## Hazard 3: publishing is always a person\'s decision',
      '',
      'Nothing in this feature ever sets a remote, pushes, or creates a',
      'repository on its own. Every one of those three actions is a button a',
      'person presses, gated by the destructive-action confirm dialog naming the',
      'exact size, file count, and destination before anything leaves the',
      'machine — a downloaded world can hold another server\'s builds, chests and',
      'coordinates. Two routes are offered: push to an existing remote, or',
      'create a new GitHub repository via `gh repo create ... --push`, with both',
      '`git` and `gh` availability (and `gh` sign-in) checked before the',
      'relevant button is even enabled.',
      '',
      '## Hazard 6: refusing to race the downloader',
      '',
      '`requestRegionAccess` is the single gate every sibling feature calls',
      'before touching a region file. It refuses, plainly, naming the exact',
      'region path and reason, whenever a live double-stat taken moments apart',
      'sees the file\'s bytes move, or the runner\'s own tracked activity for that',
      'path is inside the current quiet window. This decision',
      '(`evaluateRegionAccess`) is the second pure function tested directly.',
      'Nothing is ever queued to retry automatically.',
      '',
      '## Undo, append-only',
      '',
      'Restoring to an earlier commit is itself recorded as a **new** commit,',
      'mirroring exactly how the application\'s own local history behaves: the',
      'state being replaced is committed first if it was not already, so',
      'nothing is ever silently discarded, and the restore itself can be undone.',
      'Files present now but absent from the target commit are removed to truly',
      'match that snapshot, computed from `git diff --name-status` before',
      'anything on disk is touched.',
      '',
      '## Configuration',
      '',
      'Every setting lives under **Settings → World vault**: the world folder,',
      'the quiet period, the poll interval, whether the runner starts watching',
      'automatically, and the default visibility offered when creating a new',
      'GitHub repository (private by default).',
      '',
      '## Security considerations',
      '',
      '- No shell: every `git`/`gh` invocation runs through a real argument',
      '  array, never a string-concatenated command line.',
      '- A new repository name is validated against a strict character set',
      '  before it ever reaches `gh`.',
      '- Every mutating operation against one world\'s vault is serialized behind',
      '  a per-world-path lock in the main process, so a background commit and a',
      '  user-initiated restore can never interleave into a corrupt index.',
      '- Publishing is opt-in, every time — see hazard 3.',
      '',
      'See `docs/features/world-vault.md` in the repository for the complete',
      'article, including full verification steps and gotchas.'
    ].join('\n')
  }
];
