import type { DocArticle } from '../../core/registry';

export const WORLD_DOCS: DocArticle[] = [
  {
    id: 'mineflayerWorld.overview',
    title: 'Digging, placing, entities and the rest of the world',
    category: 'Bot world interaction',
    body: [
      '# Digging, placing, entities and the rest of the world',
      '',
      'This tab drives whichever bot session the **Minecraft bots** feature has connected. It never opens a connection itself; connect a bot from the Minecraft bots tab first.',
      '',
      'It covers rows 15.10 through 15.17 of the feature inventory, built directly from the vendored `vendor/mineflayer` library (version 4.37.1): `digging`, `place_block`, `place_entity`, `generic_place`, `block_actions`, `ray_trace`, `blocks`, `entities`, `fishing`, `bed`, `spawn_point`, `book`, `creative`, `time`, `rain`, `sound`, `particle`, `explosion`, `command_block` and `resource_pack`.',
      '',
      '## Blocks',
      '',
      'Pick a target block either by pressing **Target what the bot is looking at** (a real ray-trace through `bot.blockAtCursor`) or by typing coordinates. Then:',
      '',
      '- **Dig** shows real progress computed from the library\'s own `bot.digTime`, and refuses to start a second dig while one is already running -- the guard is checked in code before the button is even clicked, not only expressed by the button being disabled.',
      '- **Place block** and **Place entity** need a face to place against. The library\'s ray-trace does not report which face was hit through this application\'s runtime (see "Known gaps" below), so the face is a guided six-way choice of the real cardinal directions instead of a guessed vector.',
      '- **Activate** right-clicks the target block.',
      '- **Find blocks by type** searches a radius for every loaded block matching the names you list, as a sortable, filterable, exportable list.',
      '- The **block-state inspector** shows a block\'s real properties -- hardness, light, sky light, state id and its decoded block-state properties.',
      '',
      'Digging picks a tool by reading the bot\'s real inventory and equipping the chosen item to the main hand before digging starts.',
      '',
      '## Entities',
      '',
      'A live, polled list of every entity the bot currently tracks, with distance computed from the bot\'s and the entity\'s real positions (the runtime\'s own `entities` method does not report distance -- see "Known gaps"). Attacking a player always asks for confirmation naming that exact player first, because that is a consequential action against another person; attacking a non-player entity can optionally require the same confirmation through a setting.',
      '',
      '## Fishing, sleeping, spawn and respawn',
      '',
      '`bot.sleep` fails for eight distinct real reasons in the library -- wrong time of day, an occupied bed, monsters nearby, being too far away, and more -- and every one of those is shown verbatim rather than a generic "could not sleep".',
      '',
      '## Books',
      '',
      'Writing is fully working. Signing is not reachable yet -- see "Known gaps".',
      '',
      '## Creative tools',
      '',
      'Give item, set block, fly and clear inventory/slot are all present, and every one of them is disabled with the server\'s reported gamemode as the exact reason whenever the connected server is not in creative. Instant break needs no separate control: the ordinary Dig button is already instant in creative mode, because the game itself computes zero dig time there.',
      '',
      '## World ambience and command blocks',
      '',
      'Time and weather are shown in the status bar at the top of this tab. Sounds, particles and weather changes stream into a live, filterable, exportable feed as they really happen. There is no explosion feed -- again, see "Known gaps" -- and the section explains why and links to the full event inspector instead.',
      '',
      '## Resource packs',
      '',
      'A server-requested resource pack is shown honestly, with the offered URL and its accompanying identifier. Nothing here ever accepts a pack automatically; every request waits for an explicit Accept or Decline.',
      '',
      '## Known gaps',
      '',
      'Two real gaps exist between what this row of the inventory asks for and what the current build can reach, both because the change they need sits outside this feature\'s own owned files:',
      '',
      '1. **Book signing.** `../mineflayer/bot-host.js` exposes `bot.writeBook` on its method allow-list but not `bot.signBook`, even though both are real library methods with the identical validation shape. The Sign button calls a `signBook` method anyway and shows the runtime\'s own honest "not on the list of methods this runtime exposes" refusal rather than pretending to succeed. Fixing it needs one more entry added to the `METHODS` object in `../mineflayer/bot-host.js`, mirroring `writeBook` but calling `bot.signBook(slot, pages, author, title)`.',
      '2. **Explosions.** `vendor/mineflayer/lib/plugins/explosion.js` only computes blast damage (`bot.getExplosionDamages`); it never calls `bot.emit`, and the raw `explosion` protocol packet is consumed silently inside `lib/plugins/blocks.js` to update block state. The library genuinely has no explosion event to subscribe to. The Ambience section says this plainly and links to the full event inspector, which shows the `blockUpdate` events an explosion leaves behind instead of fabricating an explosion feed that does not exist.',
      '',
      'A third, smaller gap: the runtime\'s `entities` method does not report each entity\'s distance from the bot, and its `blockAtCursor` does not report which face of a block was hit. Both are computed in this feature instead of trusted from a field that is not actually sent.'
    ].join('\n'),
    related: ['mineflayer.overview', 'mineflayer.events', 'mineflayerMovement.overview', 'mineflayerWorld.gaps']
  },
  {
    id: 'mineflayerWorld.gaps',
    title: 'Digging, placing and gamemode: security and failure modes',
    category: 'Bot world interaction',
    body: [
      '# Security considerations and failure modes',
      '',
      '## Security',
      '',
      'Every call this feature makes goes through `../mineflayer`\'s allow-listed `call(botId, method, args)` bridge, which itself runs over the privileged, sandboxed `ctx.studio.process` channel to a separate Node process -- there is no `require`, no eval channel and no method the runtime host was not deliberately built to accept. This feature never talks to a socket, a file or a shell directly, and it registers no outbound HTTP allow rule because it needs none.',
      '',
      'Attacking a player always asks for an explicit, named confirmation first. Nothing in this feature ever accepts a server-offered resource pack, clears an inventory, or attacks anything without a real user action triggering it -- there is no automatic or scheduled behaviour here at all.',
      '',
      '## Failure modes',
      '',
      '- **No `mineflayer` feature present in this build.** The tab says so honestly instead of pretending to be connected, and does not render any control.',
      '- **No bot connected yet.** The tab offers a direct route to the Minecraft bots tab to connect one.',
      '- **A call is refused by the runtime.** Every refusal carries the runtime\'s own real error text (a validation failure, "not connected right now", an unknown block or item name, or a method genuinely not on the allow-list) shown through a notification, never a generic "something went wrong".',
      '- **`bot.dig`/`bot.sleep`/`bot.fish` reject mid-flight.** The real rejection reason -- including the library\'s own in-game explanations -- is shown in place, and the control that started the action is re-enabled immediately.',
      '- **The connected server is not in creative mode.** Every creative-only control is disabled with that exact fact stated as the reason.',
      '',
      '## Verification',
      '',
      'Type-checked with `npx tsc --noEmit -p tsconfig.web.json` from `app/`. Every method name this feature calls (`dig`, `stopDigging`, `digTime`, `placeBlock`, `placeEntity`, `activateBlock`, `blockAt`, `blockAtCursor`, `findBlocks`, `entities`, `attack`, `useOn`, `activateEntity`, `mount`, `dismount`, `fish`, `sleep`, `wake`, `spawnPoint`, `respawn`, `writeBook`, `acceptResourcePack`, `denyResourcePack`, `creativeStartFlying`, `creativeStopFlying`, `creativeFlyTo`, `creativeClearSlot`, `creativeClearInventory`, `creativeSetInventorySlot`, `setCommandBlock`, `inventory`, `equip`) was checked against the exact `METHODS` allow-list in `../mineflayer/bot-host.js`, and every event name this feature filters for (`diggingCompleted`, `diggingAborted`, `blockBreakProgressObserved`, `soundEffectHeard`, `hardcodedSoundEffectHeard`, `particle`, `rain`, `weatherUpdate`, `time`, `resourcePack`) was checked against that file\'s own `EVENT_NAMES` list.'
    ].join('\n'),
    related: ['mineflayerWorld.overview', 'mineflayer.overview']
  }
];
