import type { DocArticle } from '../../core/registry';

export const DOCS: DocArticle[] = [
  {
    id: 'worldvaultrenders.overview',
    title: 'Rendering a map for a World Vault commit',
    category: 'World Vault',
    body: [
      'World Vault renders turns any commit the vault has recorded into a real, ',
      'visual map. It is off by default because a single render genuinely costs ',
      'minutes of CPU time and needs a Java runtime — nothing here runs behind ',
      'your back.',
      '',
      '## What actually runs',
      '',
      'This feature drives a BlueMap-compatible renderer (the BlueMap CLI jar, or ',
      'a Worldlens Node entry point, which accepts the same arguments). It never ',
      'renders the live, actively-downloading world directly: instead, it asks ',
      '`world-vault` to check the chosen commit out to its own, separate folder — ',
      'an immutable snapshot the render can take as long as it likes over, without ',
      'racing whatever the downloader is still writing.',
      '',
      '## The queue',
      '',
      'Turning a commit into a render never happens synchronously. Every commit ',
      'goes into a queue with a configurable concurrency limit, and the queue is ',
      'the whole point: it never blocks the commit that queued it, it can be ',
      'cancelled mid-render, a failed or cancelled render can be retried, and if ',
      'commits arrive faster than they can be rendered the queue says so plainly ',
      '— labelling the oldest still-waiting entries "behind" — rather than either ',
      'freezing the application or quietly dropping the backlog.',
      '',
      'A commit that has never been rendered, was cancelled, or failed says exactly ',
      'that. It never shows a neighbouring commit\'s picture in its place.',
      '',
      '## Java and the renderer file',
      '',
      'Two things have to be true before a render can run: a Java runtime has to ',
      'be found on the machine, and a renderer file (jar or Node entry point) has ',
      'to be configured in settings. When either is missing, the failed render ',
      'names exactly which one is missing and offers the matching recovery route ',
      '— installing Java, or choosing a renderer file — rather than one generic ',
      '"render failed" message that leaves you guessing which of the two it was.',
      '',
      '## Comparing two commits',
      '',
      'The comparison surface has two independent halves. The word comparison — ',
      '"which regions differ and how many chunks" — reads the region files\' own ',
      'Anvil headers directly and needs no render at all; it works for any two ',
      'commits the moment they exist. The visual comparison needs both commits ',
      'already rendered, and opens the two finished renders side by side in your ',
      'default browser (never inside this application\'s own window, which never ',
      'loads a third-party web application by design) with a slider, a toggle, ',
      'or a plain side-by-side layout.',
      '',
      '## Disk space',
      '',
      'Every render keeps an exported snapshot and a rendered web output on disk. ',
      'This feature does not currently have a way to delete either from inside its ',
      'own interface — the settings section links straight to both folders in your ',
      'file manager instead, so old renders can be cleared by hand.'
    ].join('\n'),
    related: ['worldvault.overview', 'worldvaultedit.overview']
  },
  {
    id: 'worldvaultrenders.anvilDiff',
    title: 'How the region diff is computed',
    category: 'World Vault',
    body: [
      'The word comparison between two commits is read directly out of the Anvil ',
      'region file format this project\'s own downloader writes ',
      '(`src/main/java/game/data/region/McaFile.java`).',
      '',
      'Every region file (`r.<x>.<z>.mca`) opens with an 8192-byte header: a ',
      '4096-byte table of chunk locations, followed by a 4096-byte table of chunk ',
      'timestamps, one 4-byte big-endian entry per chunk, 1024 entries per table. ',
      'A slot whose location entry is all zero bytes has no chunk — the format\'s ',
      'own way of recording absence. Two present slots with different timestamps ',
      'mean the chunk was rewritten between the two commits, because the ',
      'timestamp is the exact second the game last saved that chunk.',
      '',
      'Comparing two commits means reading only this 8192-byte header from each ',
      'matching region file — never the full chunk data — and counting which of ',
      'the 1024 slots differ. That is what "which regions differ and how many ',
      'chunks" means here: a real count read from the files themselves, not an ',
      'estimate based on file size or modification time.'
    ].join('\n'),
    related: ['worldvaultrenders.overview']
  }
];
