import type { DocArticle } from '../../core/registry';

/**
 * The in-application article for the settings surface. It is bundled into the
 * build like every other article; nothing here fetches anything.
 */

export const SETTINGS_ARTICLE: DocArticle = {
  id: 'settings.surface',
  title: 'The settings surface',
  category: 'Navigation',
  body: [
    'Settings is a destination, and inside it every registered section is a real tab in a real tab strip. "It is only settings" is not an exemption: the strip docks to any edge, overflows rather than clipping, reorders, pins, groups, carries all four searches and both bulk closes, and remembers every one of those across restarts.',
    '',
    '## The strip',
    '',
    'Left is the default edge. A screen is wider than it is tall and a tab label is wider than it is high, so a vertical strip shows more tabs legibly than the horizontal one browsers trained everybody to expect. Docking is an orientation change rather than a rotation: no label is ever turned ninety degrees, the overflow test measures height instead of width when the strip is vertical, and the arrow keys follow the axis so a keyboard user moves with Up and Down rather than Left and Right.',
    '',
    'Right-click a settings tab for the full management menu — pin, reorder, move into a group, edit its appearance, lock it, close it — and Shift+right-click to open the appearance editor directly. The context-menu key does the same thing from the keyboard.',
    '',
    '## Four searches, not one',
    '',
    '1. The settings tab strip itself.',
    '2. Inside every individual group.',
    '3. Across groups, by their visible names.',
    '4. A master search across every settings tab, including the ones that are currently closed.',
    '',
    'Each carries its own anchored pattern builder and its own query, pattern, flags and mode. None shares hidden state with another.',
    '',
    '## The settings search is separate from, and additional to, those',
    '',
    'The search bar at the top of the surface searches every section at once: each setting\'s label, its explanation, its stable id, its keywords, its options and its CURRENT VALUE. When a match sits on a tab other than the one you are looking at, the line under the field says so and gives you a button that goes there, with the number of matches waiting on each.',
    '',
    'Plain text is the default. Regular expressions are an explicit opt-in through the toggle or the builder beside the field.',
    '',
    '## Every control is the real control',
    '',
    'A switch here is the same switch the command palette renders inline, writing to the same store through the same validation. Two routes to one value that disagree are worse than one route.',
    '',
    'Every kind is rendered: switches, text, numbers, sliders, selects, colours through the infinite picker, fonts listed from the families this machine actually has, paths, files and folders with a native browse control beside the free-text entry, actions, and controls a feature draws itself.',
    '',
    '**A browsed path and a typed path run through exactly the same checks.** A value chosen from the operating system dialog is not trusted more than one somebody typed.',
    '',
    '## Explanations and provenance',
    '',
    'Every setting carries its full explanation behind the question mark beside its name, and a provenance line underneath that says one of three things:',
    '',
    '- **From your settings file at …** — somebody actually set this, and the file is named.',
    '- **No file has ever set this. The application is using its built-in value: 8080.** — the real value is named rather than the opaque word "default", so you know what a reset will give you back.',
    '- **A schedule is setting this right now** — a scheduled rule is in charge and your own value returns when it ends.',
    '',
    '## Validation says what to do next',
    '',
    'A refused value is reported inline, in plain words, beside the control — "Must be a number between 1 and 65535" rather than a red border. Nothing is written while a value is refused, and the field keeps what you typed so you can correct it rather than start again.',
    '',
    'Every disabled control names the exact condition that is unmet, in its own tooltip and its accessible description. A disabled control with no explanation reads as broken rather than as blocked.',
    '',
    '## Selecting and acting in bulk',
    '',
    '**Select settings** turns on a checkbox on every row. Click one, then shift-click another to take the whole range; Space and Enter do the same from the keyboard. **Select every setting on this tab** and **Select every setting matching the search, on every tab** are two different actions and each says which it is, so a select-all is never ambiguous about its scope.',
    '',
    'The selection then drives **reset**, **export** and **copy the ids**. The reset counts honestly: it says how many will move and how many were already at their shipped value and will not.',
    '',
    '## Export and import',
    '',
    'Export offers every format the application supports — JSON, JSONL, YAML, TOML, XML, CSV, TSV, Markdown, HTML and SQL — and four scopes: everything, this tab, the selection, or only the settings that differ from their shipped value. Before anything is written it reports which fields the chosen format cannot carry faithfully, so a structured value flattened into a CSV cell is something you are told rather than something you discover.',
    '',
    'Credentials, the personal-vocabulary cache and the lock verifiers are never included, and the file says so in its own contents.',
    '',
    'Import reads a file this application exported, lists every key before applying anything, and separates what will be applied from what this build does not recognise and what already matches. Applying goes through the two-key confirmation gate, and every replaced value is written to local history first.',
    '',
    '## Resetting',
    '',
    'Each row has its own reset, disabled with a stated reason while the value already is the shipped one. **Reset every setting** removes every stored preference so the application falls back to what this build ships with; it goes through the two-key gate and names exactly what is not touched — credentials, toy locks and the local history.',
    '',
    'Both routes are recorded in local history, so the previous values can be read back from the history tab afterwards.',
    '',
    '## Locks',
    '',
    'Any settings tab and any individual setting can be put behind a password or a one-time code, each with its own credential. A locked setting stays visible and says it is locked, with the unlock route beside it, rather than disappearing. It is a for-fun lock and every surface says so: deleting the application data folder clears all of them.'
  ].join('\n'),
  related: ['core.tabs', 'core.palette', 'core.export', 'core.history']
};
