import type { DocArticle } from '../../core/registry';

/**
 * The documentation articles this feature bundles.
 *
 * These render through the shared in-app documentation browser and through
 * the documentation website. Everything here is plain English; the browser
 * chrome around it is what gets translated.
 */

export const DOWNLOADS_DOCS: DocArticle[] = [
  {
    id: 'downloads.overview',
    title: 'Downloads',
    category: 'Downloads',
    related: ['downloads.pairing', 'downloads.receiver', 'downloads.security'],
    body: [
      '# Downloads',
      '',
      'A small browser extension offers a browser download to World Downloader',
      'Studio before the browser takes it. The application opens its own **Start',
      'download** dialog first, showing exactly what was captured and where it',
      'would land, and nothing transfers until that dialog is confirmed.',
      '',
      '## The three surfaces',
      '',
      '1. **Start download** — a decision surface. It shows the file name, the',
      '   destination folder, the source URL, the referrer, the size and type the',
      '   server declared, and an overwrite switch. Confirming begins the exact',
      '   transfer shown; cancelling leaves the queue untouched and writes',
      '   nothing.',
      '2. **Downloading** — a separate progress window per transfer, distinct',
      '   from the list. It shows the real filename, source, destination, bytes',
      '   received, rate, an estimate when one is measurable, and controls that',
      '   pause, resume, retry, cancel, open or reveal the actual transfer.',
      '3. **Download complete** — an always-on-top completion surface. It stays',
      '   above the browser window the download came from until it is resolved',
      '   or dismissed, and it reports the honest outcome: a completed file with',
      '   its real size and path, or a failure with the real reason and however',
      '   many bytes actually arrived.',
      '',
      'All three surfaces, and the list itself, are covered in the **Downloads**',
      'tab, which also carries the search field, the bulk actions and the',
      'capture receiver’s status.',
      '',
      '## The list',
      '',
      'Every download this application has ever captured or been given by',
      'address stays in the list until it is explicitly removed. The list',
      'supports the full search field with its regular-expression builder,',
      'multi-select with a keyboard path, an honestly scoped select-all — the',
      'list has no paging, so "select all" always means every row currently',
      'matching the search — and an inverse-selection action. Bulk actions',
      'cover retry, pause, resume and removal; removing a running transfer',
      'cancels it first, and that goes through the same two-key confirmation',
      'as a single cancellation. Removing a list entry never deletes a file',
      'that already finished downloading.',
      '',
      'Every field the list shows can be exported, in every format the',
      'application supports, through the export action beside the bulk',
      'toolbar.',
      '',
      '## Configuration',
      '',
      'The **Downloads** settings section controls the default download',
      'folder, whether the capture receiver starts automatically, the',
      'loopback port it asks for, whether every capture opens the Start',
      'dialog or is asked about only once in advance, how many transfers may',
      'run at the same time, whether the application stays above the browser',
      'while a decision or a completion notice is pending, whether the',
      'Downloading window opens automatically, whether the completion',
      'surface appears at all, the Overwrite switch’s starting position, and',
      'whether a finished file is revealed in the platform file manager',
      'automatically.',
      '',
      'See **Recognising the receiver** for how the loopback receiver itself',
      'behaves, and **Pairing the browser extension** for connecting the',
      'extension to it.'
    ].join('\n')
  },
  {
    id: 'downloads.receiver',
    title: 'The capture receiver',
    category: 'Downloads',
    related: ['downloads.overview', 'downloads.pairing', 'downloads.security'],
    body: [
      '# The capture receiver',
      '',
      'The renderer cannot open a network socket or write bytes to disk as',
      'they arrive, so capturing and transferring downloads runs as a small',
      'Node.js process, started and supervised through the application’s own',
      'privileged bridge. This document describes exactly what that process',
      'does.',
      '',
      '## What it is',
      '',
      'A single script, written into the application’s own data directory on',
      'every start (never reused from a previous version) and run with',
      '`node`. It listens on **one loopback address** — `127.0.0.1` and',
      'nothing else — for capture requests from the browser extension, and it',
      'performs the transfers this application asks for.',
      '',
      'If `node` is not on this machine’s `PATH`, the Downloads tab reports',
      'that plainly: **Unavailable — Node was not found**. That is a real',
      'answer, not a failure hidden behind a spinner, and no other route is',
      'attempted.',
      '',
      '## States',
      '',
      '| State | What it means |',
      '| --- | --- |',
      '| Stopped | Not running. No captures can arrive. |',
      '| Starting… | The process has been launched and has not reported ready yet. |',
      '| Listening | Bound to the loopback address shown in the Downloads tab, with a fresh pairing token. |',
      '| Listening, with reduced reporting | Still transferring correctly, but its own stdout channel is being truncated because a very chatty session produced more output than this run retains. Restarting while nothing is transferring restores full reporting. |',
      '| Failed | Reported an error, shown verbatim. |',
      '| Unavailable — Node was not found | `node` could not be spawned on this machine. |',
      '',
      '## Restarting',
      '',
      'Starting the receiver while it is already running stops the previous',
      'process first, so the port is never left claimed by an orphaned',
      'process. A restart always issues a **fresh pairing token** — a token',
      'that stops working is the exact and only symptom of the receiver',
      'having restarted, and the Downloads tab always shows the current one.',
      '',
      'A restart never interrupts a transfer that is actively moving bytes:',
      'the receiver’s own idle-restart logic (used when its output channel',
      'approaches its retained budget) only restarts while nothing is',
      'transferring, and a manual restart from settings or the Downloads tab',
      'behaves the same way — trading a reporting channel for a real transfer',
      'is never the right trade.',
      '',
      '## Failure reporting',
      '',
      'Every state the receiver reports, and every error it raises, is the',
      'real message from Node or from the underlying HTTP request — a',
      'connection refused, a host that would not resolve, a destination',
      'drive that is full, a permission that was refused. Nothing here is a',
      'generic "something went wrong".',
      '',
      'See **Pairing the browser extension** for the other half of the',
      'connection, and **Security and privacy** for exactly what crosses',
      'this boundary.'
    ].join('\n')
  },
  {
    id: 'downloads.pairing',
    title: 'Pairing the browser extension',
    category: 'Downloads',
    related: ['downloads.overview', 'downloads.receiver', 'downloads.security'],
    body: [
      '# Pairing the browser extension',
      '',
      'The `extension` directory bundled with this application is a',
      'Manifest V3 browser extension that hands a download over to World',
      'Downloader Studio before the browser starts it. It is deliberately',
      'shipped **unpacked, or as a plain ZIP** — never as a signed `.crx`,',
      'because code signing of every kind is permanently out of scope for',
      'this project.',
      '',
      '## Installing it',
      '',
      '1. Open `chrome://extensions` (or `edge://extensions`) in a Chromium',
      '   browser.',
      '2. Switch **Developer mode** on.',
      '3. Choose **Load unpacked** and select the bundled `extension`',
      '   directory.',
      '',
      '## Pairing it',
      '',
      '1. In the **Downloads** tab, start the capture receiver if it is not',
      '   already listening.',
      '2. Open the receiver card’s **Show pairing details**. It shows the',
      '   exact loopback address and the current pairing token, each with',
      '   its own copy button.',
      '3. In the extension’s own settings, paste both values and press',
      '   **Test the connection**.',
      '4. Switch the extension’s capture toggle on.',
      '',
      'The token is regenerated every time the receiver starts. If pairing',
      'stops working, the most likely reason is that the receiver was',
      'restarted since — open the pairing details again for the current',
      'one.',
      '',
      '## What happens when nothing is listening',
      '',
      'The extension posts its handover **before** cancelling the browser’s',
      'own download. If the receiver does not answer, the browser’s own',
      'download is left running and the extension’s popup records why. A',
      'receiver that is switched off costs an interruption, never a file.',
      '',
      'See **The capture receiver** for what the receiver itself does, and',
      '**Security and privacy** for exactly what the extension sends.'
    ].join('\n')
  },
  {
    id: 'downloads.security',
    title: 'Security and privacy',
    category: 'Downloads',
    related: ['downloads.overview', 'downloads.pairing', 'downloads.receiver'],
    body: [
      '# Security and privacy',
      '',
      '## What crosses the loopback connection',
      '',
      'One JSON document per capture, to one address: `127.0.0.1` on the',
      'port the receiver is currently listening on. It carries the',
      'download’s URL, its referrer, the filename the browser suggested,',
      'the MIME type the server declared and the size the server declared.',
      'It carries **no cookies, no credentials, no page content and no',
      'browsing history**.',
      '',
      'Every request must carry the current pairing token. `credentials:',
      "'omit'` is set on the extension's own request, redirects are refused",
      'outright, and the extension asks for exactly one host permission:',
      '`http://127.0.0.1/*`. It can reach nothing else, and nothing outside',
      'this machine can reach the receiver — it listens on the loopback',
      'interface only.',
      '',
      '## Where a captured filename can and cannot lead',
      '',
      'The filename a capture suggests comes from the remote server’s',
      '`Content-Disposition` header by way of the browser, which makes it',
      'attacker-influenced text. Before it is ever offered as a suggestion,',
      'every path separator, every traversal segment (`..`), every control',
      'character and every reserved Windows device name (`CON`, `PRN`,',
      '`NUL`, `COM1`–`COM9`, `LPT1`–`LPT9`) is stripped or replaced. A',
      'capture can suggest a name; it can never decide a path outside the',
      'folder the user chose in the Start download dialog.',
      '',
      '## What the destination folder requires',
      '',
      'The Start download dialog refuses a folder that is not an absolute',
      'path, with the exact reason shown and the typed value kept so nothing',
      'already entered has to be retyped. A relative path, were one ever',
      'accepted, could resolve unpredictably depending on where the process',
      'happens to be running from; an absolute path removes that ambiguity',
      'entirely.',
      '',
      '## What is never written anywhere it should not be',
      '',
      'The pairing token is generated fresh on every receiver start, handed',
      'to the receiver process over its **standard input** (never a command',
      'line argument, an environment variable or a settings file — a command',
      'line is visible to every other process on the machine; standard input',
      'is not), and never placed in an export, a log line the application',
      'keeps, or local history.',
      '',
      '## What removing a list entry does, and does not do',
      '',
      'Removing entries from the downloads list is recorded in local',
      'history like any other change, and it goes through the two-key',
      'destructive-action gate whenever it would cancel a transfer that is',
      'still moving bytes. It only ever deletes the *list entry* and, for a',
      'running transfer being cancelled, the *partial file* that transfer',
      'was writing. A file that already finished downloading is never',
      'touched by removing its row from the list.',
      '',
      'See **The capture receiver** and **Pairing the browser extension**',
      'for the surfaces this protects.'
    ].join('\n')
  }
];
