import type { DocArticle } from '../../core/registry';

export const WORLD_VAULT_EDIT_DOCS: DocArticle[] = [
  {
    id: 'worldvaultedit.overview',
    title: 'Chunk operations from the map',
    category: 'World vault',
    body: [
      'This feature copies or removes chunks in a downloaded world, driven from a',
      'real occupancy grid read off the actual region files on disk.',
      '',
      '## What it does',
      '',
      '- **Select** one chunk or a rectangle of chunks, by click, Shift-click,',
      '  Ctrl/Cmd-click, or entirely from the keyboard.',
      '- **Copy** the selection to another coordinate. This is not a byte copy: a',
      '  chunk carries its own coordinates (`xPos`/`zPos`) and every block entity',
      '  and entity inside it carries an absolute position, and all of it is',
      '  rewritten to the new location, including the separate `entities/*.mca`',
      '  companion file when the world uses one.',
      '- **Remove** the selection, clearing each chunk’s entry so the game treats',
      '  it as never generated and rebuilds it next time it loads.',
      '- Every edit is recorded as a real commit in the world’s own vault (kind',
      '  `edit`), so it is covered by the vault’s unlimited undo exactly like a',
      '  downloaded snapshot — restore it from the World vault tab.',
      '',
      '## Why a copy rewrites coordinates',
      '',
      'A chunk’s NBT is not self-contained the way a picture would be. Its own',
      'coordinates are stored inside it, and so is every block entity’s (a',
      'chest, a sign, a command block) and every entity’s (a mob, an item frame,',
      'a moving item) absolute block position. Copying the raw bytes to a new',
      'region-file slot would leave a chunk that renders in the wrong place, or',
      'that the game refuses to load at all. This feature reads the project’s own',
      'region-file writer (`src/main/java/game/data/region/McaFile.java`,',
      '`ChunkBinary.java`, `Chunk.java`, `ChunkEntities.java`) as the authority on',
      'the exact byte layout and field names, rather than reasoning about the',
      'Anvil format from memory, and rewrites every one of those positions before',
      'writing the copy.',
      '',
      '## Why an edit can be refused',
      '',
      'If the downloader (or another edit) is still writing to a region file this',
      'action needs, the edit is refused outright — never queued to run later —',
      'naming the exact region and the reason. Editing a region file mid-write is',
      'a race that can corrupt the world; the world vault’s own permission check',
      'is what decides when a region has gone quiet enough to touch safely.',
      '',
      '## How the write actually happens',
      '',
      'The privileged bridge has no channel for raw binary file writes, so the',
      'actual region-file surgery runs as a small, dependency-free Node.js',
      'script, materialised to disk and spawned as a real process (`node` is',
      'already on the application’s allow-listed command list). Every write is',
      'atomic — written to a temporary file, verified by reading it back from',
      'disk, and only then renamed into place — so a write that does not verify',
      'leaves the original file completely untouched rather than half-written.'
    ].join('\n'),
    related: ['core.overview', 'downloader.overview', 'map.overview']
  }
];
