import type { DocArticle } from '../../core/registry';

/**
 * The bundled documentation for this feature.
 *
 * It is deliberately explicit about the one limit a user will otherwise
 * discover by pressing a button and watching nothing happen: an editor this
 * application does not know how to launch can be stored and verified, but not
 * started, and the surface says which of those two an entry is.
 */

export const externalEditorDocs: DocArticle[] = [
  {
    id: 'external-editor.overview',
    title: 'Opening things in an external editor',
    category: 'External editor',
    body: [
      'Anything this application can point at on disk can be handed to an editor: an export that was just written, a folder you work in, or a path you browse for by hand. Visual Studio Code is the first-class target, and a folder is handed over as a **workspace root** rather than as one lonely file, because a file tree is the whole reason to open a folder in an editor.',
      '',
      '## What the surface shows',
      '',
      'The **External editor** tab lists every editor the application knows about, in four states:',
      '',
      '| State | What it means |',
      '| --- | --- |',
      '| Installed and ready | Found on this machine by the probe. A handoff starts it. |',
      '| The same file as a detected editor | You added this executable yourself and it turned out to be one the application already knows how to start. A handoff starts it. |',
      '| Not on this machine | Known by name, but the executable is not here. |',
      '| Present, but cannot be started | You added this executable, it exists on disk, and it is not one of the editors this application knows how to launch. |',
      '',
      'The last row is the honest one. A handoff runs one of the editors the privileged part of the application knows how to launch; it does not run an arbitrary program chosen in the interface, because that would be a general "run anything" capability wearing an editor\'s label. An entry in that state keeps its **Open** button disabled and names exactly that reason, and two routes that do work are offered beside it: opening the path with the operating system\'s default application, and showing it in the file manager. Neither of those pretends to be the editor you chose.',
      '',
      '## Detection',
      '',
      'The probe looks for each known editor twice: as a bare command on `PATH`, and then at the usual per-user and machine install locations. Visual Studio Code, Visual Studio Code Insiders and VSCodium are tried first, in that order, and are the editors that can open a folder as a workspace root.',
      '',
      'Detection runs when the application starts — that can be turned off — and on demand from **Re-check**. Re-checking also verifies every executable you added against the disk, so an editor that has been uninstalled or moved since the last launch stops claiming to be there instead of failing at the moment somebody uses it.',
      '',
      '## Choosing which editor is used',
      '',
      'The active editor is either **Choose automatically**, which prefers Visual Studio Code and falls back through the rest of its family, or one you pick. An explicit choice that cannot be started opens nothing and says so; it never silently starts something else, because a Notepad window appearing where Visual Studio Code was asked for explains nothing about itself.',
      '',
      'The picker is built from what the machine actually reported, not from a written-down list, so it can never offer an editor that is not there.',
      '',
      '## Adding an editor',
      '',
      'Browse for the executable. The path is verified against the disk before it is stored, a duplicate is refused by naming the entry that already holds it, and the name defaults to the file name when you do not give one. Forty stored editors is the ceiling.',
      '',
      '## When nothing is found',
      '',
      'The surface says so in plain words and offers the Visual Studio Code download, which opens `code.visualstudio.com` **in your browser**. The application itself downloads nothing, fetches nothing and makes no request of its own.',
      '',
      '## Failure modes',
      '',
      '- **The probe itself fails.** The list falls back to the editors you added yourself and the exact failure text is shown above the table. Nothing is invented to fill the gap.',
      '- **The path has moved.** A handoff verifies the path before launching, so the message names the path rather than reporting a mysterious editor failure.',
      '- **A folder was asked for and the editor cannot open one.** The handoff is refused with the editor\'s name in the message, rather than downgraded to opening the file on its own.',
      '- **The editor refuses to start.** The exact text from the operating system is shown and recorded in the recent list, so it can be read again after the notification has gone.',
      '',
      '## Security',
      '',
      'Launching is done by the privileged part of the application, which starts a known editor by its identifier with the target path as its only argument. No shell is involved, so nothing in a path can be interpreted as a command. The interface cannot ask for an arbitrary program to be run, which is why an unrecognised executable is stored but not started.',
      '',
      'Nothing here reaches the network. The download button opens a page in your browser; it is the only outbound step and it is yours, not the application\'s.',
      '',
      '## Verification',
      '',
      'What to check by hand, on a machine with Visual Studio Code installed and again on one without it:',
      '',
      '1. Open the tab. The list names Visual Studio Code as installed and ready, or says plainly that nothing usable was found.',
      '2. Browse for a file, leave the mode on "the file on its own", and open it. The editor opens that file.',
      '3. Switch to "its folder as a workspace root" and open the same file. The editor opens the containing folder with its tree.',
      '4. Set the project folder in Settings and use **Open the project folder**. The same folder opens as a workspace root.',
      '5. Choose an editor that is not installed as the active one. The **Open** button goes disabled and names it.',
      '6. Add an executable that is not an editor the application knows. It is stored, verified and listed as present but not startable, and its Open route is disabled with that reason.',
      '7. Search the list, select rows with Shift held, and export the selection in two different formats. The preflight names any field the format cannot carry before anything is written.'
    ].join('\n'),
    related: ['external-editor.troubleshooting', 'core.export', 'core.overview']
  },
  {
    id: 'external-editor.troubleshooting',
    title: 'When the editor does not open',
    category: 'External editor',
    body: [
      'Every refusal in this feature is a sentence naming the exact cause. This article is the map from that sentence to what to do about it.',
      '',
      '## "No editor this application can start was found on this machine"',
      '',
      'The probe ran and found nothing. Install Visual Studio Code — the button beside the message opens its download page in your browser — and then choose **Re-check**. If it is already installed somewhere unusual, browse for its executable in **Add an editor**: it will be recognised as the same file the application knows and become startable.',
      '',
      '## "The chosen editor cannot be started from here"',
      '',
      'You picked an editor explicitly and it is no longer available. Pick another, or go back to **Choose automatically**. Nothing is started in its place, on purpose.',
      '',
      '## "cannot open a folder as a workspace root"',
      '',
      'The editor is installed but is not one that takes a directory. Open the file on its own instead, or choose an editor from the Visual Studio Code family.',
      '',
      '## "There is nothing at that path on this machine"',
      '',
      'The path was checked immediately before the handoff and is gone. This is the usual outcome of a stored recent handoff whose file has since been deleted or moved.',
      '',
      '## "this application cannot start it"',
      '',
      'The executable you added is real and verified, and it is not one of the editors the application knows how to launch. Use **Open with the default application** or **Show in the file manager**; both work, and both say what they are rather than pretending to be the editor.',
      '',
      '## The probe fails outright',
      '',
      'The exact failure text appears above the editor list and only editors you added yourself are listed. Nothing is guessed to fill the gap. Re-check retries it.',
      '',
      '## Where the record is',
      '',
      'Every handoff, successful or refused, is kept in **Recent handoffs** with its exact failure text, so an error can be read again after the notification is gone. That list has the same search, bulk actions and export as every other list, and forgetting an entry removes the record only — no file is touched.',
      '',
      'Every change to the stored editors, and every handoff, is written to local history, so what happened is auditable after the fact.'
    ].join('\n'),
    related: ['external-editor.overview', 'core.history', 'core.export']
  }
];
