/**
 * The in-application documentation for the logo feature.
 *
 * Written as Markdown and rendered by the shared renderer. No image, font or
 * script is referenced from anywhere outside this build, because the docs
 * browser is offline like the rest of the application.
 */

import type { DocArticle } from '../../core/registry';
import { LIMITS, TARGET_SIZES } from './imageBytes';
import { PRESETS } from './presets';

const OVERVIEW = [
  'The application logo is the mark drawn beside the product name in the title bar.',
  'It ships with a set of vector marks, and it accepts an image of your own, which is',
  'converted here on this computer into the exact sizes the application draws.',
  '',
  '## What it changes, and what it never changes',
  '',
  'The mark is **presentation only**. Choosing one changes what you look at and nothing else.',
  'The package identity, the application id, the executable filename, the installer identity,',
  'the update feed and the data directory are all set by the build, and no choice on this page',
  'moves any of them. That boundary is not a promise you have to take on trust: the logo tab',
  'prints the package identity, the shipped product name, the version and the data directory',
  'beside the picker, so you can watch them stay put across a change.',
  '',
  'This matters more than it sounds. An application whose data directory was derived from its',
  'presentation would orphan every stored profile, credential and history entry the first time',
  'somebody changed their mind about an icon.',
  '',
  '## The shipped marks',
  '',
  ...PRESETS.map((preset) => `- **${preset.id}** — ${preset.keywords.join(', ')}`),
  '',
  'Each is drawn as inline vector geometry rather than shipped as an image file, so it follows',
  'your seed colour, contrast level and theme, needs no conversion, and stays sharp at every size.',
  '',
  '## Using your own image',
  '',
  'Choose a file and the bytes are read, checked and decoded inside this window. Nothing is',
  'uploaded, no converter runs on another machine and no network request is made at any point.',
  '',
  '### What is accepted',
  '',
  '| Rule | Value |',
  '| --- | --- |',
  '| Formats | PNG, JPEG, WebP, BMP |',
  `| Maximum file size | ${LIMITS.maxSourceBytes} bytes |`,
  `| Smallest side | ${LIMITS.minDimension} pixels |`,
  `| Largest side | ${LIMITS.maxDimension} pixels |`,
  `| Maximum decoded pixels | ${LIMITS.maxPixels} |`,
  `| Decode time budget | ${LIMITS.decodeTimeoutMs} ms |`,
  `| Generated sizes | ${TARGET_SIZES.join(', ')} |`,
  `| Total size of the generated set | ${LIMITS.maxTotalOutputBytes} bytes |`,
  '',
  'The **bytes** are checked, never the file name. A file called `logo.png` that is really',
  'something else is identified from its own signature and refused by name.',
  '',
  '### What is refused, and why',
  '',
  '- **Animated PNG, animated WebP and every GIF.** The output is seven fixed still images, so',
  '  an animation has nowhere to go. Save the frame you want and choose that.',
  '- **SVG and other markup.** An SVG is a document that can carry scripts and references to',
  '  other files. Export the drawing as a PNG first.',
  '- **Icon containers and TIFF.** These hold several images at once; pick the one you mean.',
  '- **A file that disagrees with itself.** If the header says one size and the decoder produces',
  '  another, the file is refused rather than trusted.',
  '',
  'A refusal never changes anything. The mark in use stays exactly where it was.',
  '',
  '## Framing',
  '',
  'The crop rectangle can be dragged, or resized by its four corners. From the keyboard, focus',
  'a corner and use the arrow keys; hold <kbd>Shift</kbd> for larger steps. The four numeric',
  'fields underneath are the same value by another route, so either can be used.',
  '',
  '- **Contain** keeps the whole cropped image inside the square.',
  '- **Cover** fills the square and crops whatever hangs over.',
  '- **Fill** stretches to the square and does not preserve the aspect ratio.',
  '',
  'The focal point decides which part survives when the image does not exactly fill the square.',
  'The background is transparent by default; turning transparency off paints the chosen colour',
  'behind the image, and the picker reports the contrast against the window surface so a mark',
  'that would disappear into the chrome says so before it is applied.',
  '',
  'The safe-area guide draws a ring over the previews showing what a circular mask would keep.',
  'It is a guide only and never appears in the output.',
  '',
  '## Conversion',
  '',
  'Conversion writes one PNG per display size and verifies each one four ways before it counts:',
  'the PNG signature, the declared dimensions, an RGBA colour type so transparency survives, and',
  'a decoder round-trip. A variant that fails any of those stops the whole conversion, and the',
  'previous mark stays in use — a half-applied logo is worse than an unchanged one.',
  '',
  'Everything the conversion will change is listed **before** you press the button:',
  're-encoding, colour-profile flattening, transparency removal, cropping, stretching, and which',
  'sizes will be enlarged or shrunk. Nothing is discovered afterwards.',
  '',
  '## School mode',
  '',
  'School mode hides the Cantonese, bilingual, humour-level, personal-vocabulary and dim sum',
  'capabilities wherever they are offered. This feature offers none of them: it has no language',
  'control, no humour control, no vocabulary control and no dim sum surface of its own, so there',
  'is nothing here for the mode to omit. Its copy is still rendered through the shared resolver,',
  'so it follows whatever language and humour level the application is in — including the forced',
  'English that School mode applies everywhere at once.',
  '',
  '## Where the data lives',
  '',
  'The generated sizes are stored in the application settings file. The **original image is not**',
  '**kept**, and neither is its path or its file name. That is deliberate: the application does',
  'not need a copy of a picture from your disk in order to draw a mark, so it does not take one.',
  'Re-cropping after a restart means choosing the file again, and the editor says so rather than',
  'pretending otherwise.',
  '',
  'The image data is also left out of exports, history entries and logs. Exports carry names,',
  'sizes, byte counts and verification results, and say plainly that the pixels were omitted.',
  '',
  '## Failure modes',
  '',
  '| What happens | What you see |',
  '| --- | --- |',
  '| The file is refused | The exact reason, on the upload status line and as a notification. Nothing changes. |',
  '| Decoding takes too long | The decode is stopped at the time budget and reported. Nothing changes. |',
  '| A generated size fails verification | The conversion stops and names the size and the check that failed. The previous mark stays. |',
  '| The generated set exceeds the byte budget | The exact total and the ceiling are reported. Nothing is applied. |',
  '| The stored choice cannot be rendered | The shipped icon is shown and the tab says which choice failed. |',
  '| The title bar cannot be found | The mark is still saved, and the state line says the screen did not change. |',
  '',
  '## Verification',
  '',
  'To check the feature end to end:',
  '',
  '1. Choose each shipped mark in turn and watch the title bar follow.',
  '2. Choose a PNG with transparency, crop it, and confirm the transparency notice appears only',
  '   after the transparent background is switched off.',
  '3. Rename a text file to `.png` and choose it: it is refused by signature, not by name.',
  '4. Convert, then read the generated sizes table — every row should say Verified.',
  '5. Re-verify a selection and confirm the count reported matches the selection.',
  '6. Restart, and confirm the mark is still in use and the editor honestly reports that the',
  '   original image is no longer loaded.',
  '7. Compare the package identity and data directory printed in the tab before and after a',
  '   change; they must be identical.'
].join('\n');

export const ARTICLES: DocArticle[] = [
  {
    id: 'appLogo.overview',
    title: 'The application logo',
    category: 'Appearance',
    body: OVERVIEW,
    related: ['appLogo.privacy']
  },
  {
    id: 'appLogo.privacy',
    title: 'What the logo pipeline does with your image',
    category: 'Appearance',
    body: [
      'A logo pipeline handles a file the user chose from their own disk, so it is worth being',
      'exact about where that file goes.',
      '',
      '## It goes nowhere',
      '',
      '- No network request is made at any stage. There is no upload, no CDN, no remote converter',
      '  and no analytics call. The application-wide content security policy closes outbound',
      '  connections from this window, and the privileged bridge is deny-by-default for HTTP.',
      '- The decoding, cropping and rasterization all happen in this window, using the browser',
      '  engine the application already ships.',
      '- The original file is never copied into application storage. Only the generated sizes are',
      '  kept, and only in the settings file the application already owns.',
      '- The source path and file name are never stored, exported or recorded in history.',
      '',
      '## What a history entry records',
      '',
      'A conversion records the source format, the source dimensions, which sizes were produced,',
      'the total byte count and which losses applied. It records **no image data**, so the history',
      'never becomes a second copy of your picture in a different file.',
      '',
      '## What an export contains',
      '',
      'Exports carry names, sizes, byte counts and verification results. The image data is left',
      'out on purpose and the export surface says so before you press the button.',
      '',
      '## Bounds',
      '',
      'Every stage has a hard ceiling: input bytes, decoded pixels, each dimension, decode time,',
      'the number of outputs and the total size of the output set. A file that exceeds any of them',
      'is refused with the exact number, and nothing is partially applied.'
    ].join('\n'),
    related: ['appLogo.overview']
  }
];
