/**
 * World Downloader Studio — the application mark, inline.
 *
 * Generated by app/scripts/generate-icons.mjs from the same geometry that
 * produces build/icon.svg and build/icon.ico, so the mark in the title bar is
 * the mark on the taskbar. Do not hand-edit: re-run the generator instead.
 *
 * The mark is an inline string rather than a file reference on purpose. Nothing
 * here loads over the network and nothing reaches for a file:// URL at runtime,
 * so the title bar, the About surface and every empty state draw the mark with
 * no request of any kind.
 */

/** The design space every coordinate in the mark is expressed in. */
export const APP_LOGO_VIEWBOX = '0 0 512 512';

/** The product name, used as the accessible name when the caller supplies none. */
export const APP_LOGO_DEFAULT_TITLE = 'World Downloader Studio';

/**
 * The single-colour silhouette: the cube outline with the arrow as a hole in it,
 * separated by the even-odd fill rule. It paints in `currentColor`, so it takes
 * the colour of whatever surface it sits on and stays legible in both themes.
 */
export const APP_LOGO_SILHOUETTE_PATH =
  'M 256 52 L 440 156 L 440 356 L 256 460 L 72 356 L 72 156 Z M 212 104 L 300 104 L 300 268 L 350 268 L 256 394 L 162 268 L 212 268 Z';

export interface AppLogoOptions {
  /** Rendered edge length in CSS pixels. The mark is square. Defaults to 24. */
  size?: number;
  /**
   * Accessible name. Ignored when `decorative` is true. Defaults to the product
   * name, which is the right answer wherever the mark stands in for the product.
   */
  title?: string;
  /**
   * True when the mark sits beside text that already names the product. The
   * element is then hidden from assistive technology instead of announcing the
   * product name a second time.
   */
  decorative?: boolean;
  /** Extra class names for the root element. */
  className?: string;
}

let instanceCounter = 0;

/**
 * Gradient and clip-path identifiers are document-wide in SVG, so two copies of
 * the mark on one surface would otherwise fight over them.
 */
function nextInstanceId(): string {
  instanceCounter += 1;
  return `wds-logo-${instanceCounter}`;
}

function escapeXml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

function rootAttributes(options: AppLogoOptions): string {
  const size = options.size ?? 24;
  const className = options.className ? ` class="${escapeXml(options.className)}"` : '';
  const label = options.decorative
    ? ' aria-hidden="true" focusable="false"'
    : ` role="img" aria-label="${escapeXml(options.title ?? APP_LOGO_DEFAULT_TITLE)}"`;
  return `xmlns="http://www.w3.org/2000/svg" viewBox="${APP_LOGO_VIEWBOX}" width="${size}" height="${size}"${className}${label}`;
}

/**
 * The artwork itself. `id` scopes the gradient and clip-path identifiers to one
 * instance so two copies of the mark on the same surface cannot fight over them.
 */
function appLogoArtwork(id: string): string {
  return `
  <defs>
    <linearGradient id="${id}-backdrop" x1="0" y1="0" x2="0" y2="512" gradientUnits="userSpaceOnUse">
      <stop offset="0" stop-color="#0D8F4E"/>
      <stop offset="1" stop-color="#00382C"/>
    </linearGradient>
    <clipPath id="${id}-topface">
      <polygon points="256,52 440,156 256,260 72,156"/>
    </clipPath>
  </defs>
  <!-- Backdrop: a rounded square so the mark holds its shape on a light desktop and a dark one. -->
  <rect x="0" y="0" width="512" height="512" rx="112" ry="112" fill="url(#${id}-backdrop)"/>
  <!-- The chunk: three faces of an isometric cube. -->
  <polygon points="256,52 440,156 256,260 72,156" fill="#B6FFCE"/>
  <polygon points="72,156 256,260 256,460 72,356" fill="#62DE89"/>
  <polygon points="256,260 440,156 440,356 256,460" fill="#22A85F"/>
  <!-- Map grid, clipped to the top face. -->
  <g clip-path="url(#${id}-topface)" fill="#0D8F4E" fill-opacity="0.3">
    <polygon points="346.28,100.95 162.28,204.95 165.72,211.05 349.72,107.05"/>
    <polygon points="162.28,107.05 346.28,211.05 349.72,204.95 165.72,100.95"/>
  </g>
  <!-- The download arrow, filled with the backdrop so it reads as a shape cut through the chunk. -->
  <polygon points="212,104 300,104 300,268 350,268 256,394 162,268 212,268" fill="url(#${id}-backdrop)"/>`;
}

/**
 * The full-colour mark, as an SVG string ready to assign to `innerHTML` on a
 * container the application owns.
 */
export function appLogoSvg(options: AppLogoOptions = {}): string {
  const id = nextInstanceId();
  return `<svg ${rootAttributes(options)}>${appLogoArtwork(id)}
</svg>`;
}

/**
 * The single-colour mark. Use it in a title bar, a menu row or anywhere the mark
 * has to sit at small size in the surrounding text colour.
 */
export function appLogoMonochromeSvg(options: AppLogoOptions = {}): string {
  return [
    `<svg ${rootAttributes(options)}>`,
    `  <path d="${APP_LOGO_SILHOUETTE_PATH}" fill="currentColor" fill-rule="evenodd"/>`,
    '</svg>'
  ].join('\n');
}

/**
 * The full-colour mark as a `data:` URI, for the places that need an image
 * source rather than markup. It encodes the markup already in memory; it never
 * fetches anything.
 */
export function appLogoDataUri(options: AppLogoOptions = {}): string {
  return `data:image/svg+xml;charset=utf-8,${encodeURIComponent(appLogoSvg(options))}`;
}
